# Generated by Django 4.0.3 on 2022-04-10 10:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name': 'О Компании',
                'verbose_name_plural': 'О Компании',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('phone_number2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона (Не обязательно)')),
                ('description', models.TextField(verbose_name='Краткое описани для страницы контакты')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('work_from', models.TextField(max_length=255, verbose_name='График работы')),
                ('site_title_name', models.CharField(max_length=255, verbose_name='Название сайта на хедере')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Название вопроса')),
                ('answer', models.TextField(max_length=255, verbose_name='Ответ вопроса')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=200)),
                ('context', tinymce.models.HTMLField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Доп. Страница',
                'verbose_name_plural': 'Доп. Страницы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок слайда')),
                ('description', models.TextField(verbose_name='Описание на слайде')),
                ('link', models.CharField(default='#', max_length=300, verbose_name='Ссылка на продук')),
                ('background', models.ImageField(upload_to='slides', verbose_name='Задний фон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включить/Выключить')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
