# Generated by Django 4.0.3 on 2022-04-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('detail', models.CharField(max_length=255, verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Характеристрика (Ширина)',
                'verbose_name_plural': 'Характеристрики',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.CharField(db_index=True, max_length=200, verbose_name='краткое описание')),
                ('image', models.ImageField(blank=True, default='static/no_image.png', null=True, upload_to='category/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Категрия',
                'verbose_name_plural': 'Категрии',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Описание продукта')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('sale', models.IntegerField(default=0, verbose_name='Скидка')),
                ('hots', models.BooleanField(default=False, verbose_name='Новинки')),
                ('in_home', models.BooleanField(default=False, verbose_name='На главную')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(related_name='attributes', to='shop.attributes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='static/no_image.png', upload_to='products/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
